# Experiment 0

## Problem Statement


Perform the following Numpy Operations:

- Create a 1D NumPy array with values from 0 to 9.
- Create a 2D array with shape (3, 4) filled with random integers.
- Reshape the 2D array into a new shape (4, 3).
- Extract the third element from a 1D array.
- Get the last two columns from a 2D array.
- Create a 3x3 matrix with values ranging from 0 to 8 and extract the diagonal elements.
- Perform element-wise multiplication of two arrays.
- Calculate the mean, median, and standard deviation of an array.
- Normalize the values in a 1D array to the range [0, 1].
- Concatenate a 1D array with itself three times.
- Replace all even elements in an array with their negative values.
- Add a constant value to each column of a 2D array.
- Perform element-wise addition of two matrices A and B.
- Subtract matrix B from matrix A element-wise.
- Multiply each element of matrix A by a scalar value.
- Reshape a 1D array into a 2D array (e.g., from (9,) to (3,3)).
- Flatten a 2D array into a 1D array.
- Transpose a 2D array.


## Code


In [4]:
# importing libraries
import numpy as np

### Create a 1D NumPy array with values from 0 to 9.


In [5]:
# Create a 1D NumPy array with values from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create a 2D array with shape (3, 4) filled with random integers.


In [6]:
# Create a 2D array with shape (3, 4) filled with random integers
a = np.random.randint(0, 10, (3, 4))
print(a)

[[9 6 2 0]
 [8 3 7 7]
 [0 6 9 9]]


### Reshape the 2D array into a new shape (4, 3).


In [7]:
# Reshape the 2D array into a new shape (4, 3)
b = a.reshape(4, 3)
print(b)

[[9 6 2]
 [0 8 3]
 [7 7 0]
 [6 9 9]]


### Extract the third element from a 1D array.


In [17]:
# Extract the third element from a 1D array
arr = np.arange(10)
print(arr[2])

2


### Get the last two columns from a 2D array.


In [16]:
# Get the last two columns from a 2D array
arr = np.arange(9).reshape(3, 3)
print(arr[:, 1:])

[[1 2]
 [4 5]
 [7 8]]


### Create a 3x3 matrix with values ranging from 0 to 8 and extract the diagonal elements.


In [10]:
# Extract the last two elements from a 1D array
print(arr[-2:])

[8 9]


### Perform element-wise multiplication of two arrays.


In [12]:
# Perfrom element-wise multiplication of two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.multiply(a, b)
print(c)

[ 5 12 21 32]


### Calculate the mean, median, and standard deviation of an array.


In [20]:
# Calculate the mean, meduan, and standard deviation of an array
arr = np.arange(10)
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))

Mean:  4.5
Median:  4.5
Standard Deviation:  2.8722813232690143


### Normalize the values in a 1D array to the range [0, 1].


In [22]:
# Normalize the values in a 1D array to the range [0, 1]
arr = np.arange(10)
print("Normalized Array: ", (arr - arr.min()) / (arr.max() - arr.min()))

Normalized Array:  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Concatenate a 1D array with itself three times.


In [23]:
# Concatenate a 1D array with itself three times
arr = np.arange(5)
print(np.concatenate((arr, arr, arr)))


[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


### Replace all even elements in an array with their negative values.


In [24]:
# replace all even elements in an array with their negative values
arr = np.arange(10)
arr[arr % 2 == 0] *= -1
print(arr)


[ 0  1 -2  3 -4  5 -6  7 -8  9]


### Add a constant value to each column of a 2D array.


In [25]:
# add a constant value to each colmn of a 2d array
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Perform element-wise addition of two matrices A and B.


In [26]:
# perfrom element wise addition of two matrices A and B
a = np.arange(9).reshape(3, 3)
b = np.arange(9).reshape(3, 3)
print(a + b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### Subtract matrix B from matrix A element-wise.


In [34]:
# perfrom element wise subtraction of two matrices A and B
a = np.arange(9).reshape(3, 3)
b = np.arange(9).reshape(3, 3)
print(a - b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Multiply each element of matrix A by a scalar value.


In [35]:
# multiply each element of matrix A by a scalar value
a = np.arange(9).reshape(3, 3)
print(a * 2)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### Reshape a 1D array into a 2D array (e.g., from (9,) to (3,3)).


In [36]:
# reshape a 1D array into a 2D array 
arr = np.arange(10)
print(arr.reshape(2, 5))


[[0 1 2 3 4]
 [5 6 7 8 9]]


### Flatten a 2D array into a 1D array.


In [38]:
# flatten a 2D array into a 1D array
arr = np.arange(10).reshape(2, 5)
print(arr.flatten())

[0 1 2 3 4 5 6 7 8 9]


### Transpose a 2D array.


In [43]:
# transpose a 2D array
arr = np.arange(10).reshape(2, 5)
print("Original Array: \n", arr)
print("\n")
print("Transpose: \n", arr.T)

Original Array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Transpose: 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
