## Problem Statement

To perform various operations like reshape, resize, linspace, eye and ones on NumPy.

In [2]:
import numpy as np

resize

In [3]:
a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


linspace

In [4]:
c = np.linspace(1, 10, 10)
print(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


eye

In [5]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ones

In [6]:
e = np.ones((3, 3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
